openapi: 3.0.1
info:
  title: Writer One
  version: "v1"
servers:
  - url: https://writer-one.com
paths:
  /addToDoc/{docId}:
    post:
      operationId: addToDoc
      summary: Append content to the document using the specified document ID.
      x-openai-isConsequential: false
      parameters:
        - in: path
          name: docId
          required: true
          schema:
            type: string
          description: Unique identifier for the document.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        "200":
          description: Ok
  /getCompletedDoc/{docId}:
    get:
      operationId: getCompletedDoc
      summary: Append the final piece of content using the specified document ID and return the complete document.
      x-openai-isConsequential: false
      parameters:
        - in: path
          name: docId
          required: true
          schema:
            type: string
          description: Unique identifier for the document.
      responses:
        "200":
          description: Document url for the user to access
          content:
            text/plain:
              schema:
                type: string
